#!/usr/bin/env bash
set -euo pipefail
AWS_REGION="${AWS_REGION:-us-gov-west-1}"
PARAMETER_PREFIX="${PARAMETER_PREFIX:-/aurora-sre-agent}"
: "${RUNBOOK_BUCKET_NAME:?Set RUNBOOK_BUCKET_NAME}"
: "${ALARM_QUEUE_URL:?Set ALARM_QUEUE_URL}"
: "${AUDIT_BUCKET_NAME:?Set AUDIT_BUCKET_NAME}"
: "${DYNAMODB_TABLE_NAME:?Set DYNAMODB_TABLE_NAME}"
: "${SMTP_HOST:?Set SMTP_HOST}"
: "${SMTP_SENDER:?Set SMTP_SENDER}"
: "${SMTP_DEFAULT_RECIPIENTS:?Set SMTP_DEFAULT_RECIPIENTS}"
: "${SERVICENOW_INSTANCE_URL:?Set SERVICENOW_INSTANCE_URL}"
: "${BEDROCK_MODEL_ID:?Set BEDROCK_MODEL_ID}"
put_param() {
  aws ssm put-parameter --name "${PARAMETER_PREFIX}/$1" --type "SecureString" --value "$2" --overwrite --region "${AWS_REGION}" >/dev/null
}
put_param "runbooks/s3_bucket" "${RUNBOOK_BUCKET_NAME}"
put_param "runbooks/database/key" "runbooks/database_runbook.md"
put_param "runbooks/infrastructure/key" "runbooks/infrastructure_runbook.md"
put_param "runbooks/application/key" "runbooks/application_runbook.md"
put_param "runbooks/max_chars" "18000"
put_param "runbooks/refresh_interval_seconds" "300"
put_param "sqs/queue_url" "${ALARM_QUEUE_URL}"
put_param "audit/s3_bucket" "${AUDIT_BUCKET_NAME}"
put_param "audit/s3_prefix" "audit"
put_param "dynamodb/table_name" "${DYNAMODB_TABLE_NAME}"
put_param "smtp/host" "${SMTP_HOST}"
put_param "smtp/port" "${SMTP_PORT:-587}"
put_param "smtp/sender" "${SMTP_SENDER}"
put_param "smtp/username" "${SMTP_USERNAME:-}"
put_param "smtp/password" "${SMTP_PASSWORD:-}"
put_param "smtp/use_tls" "${SMTP_USE_TLS:-true}"
put_param "smtp/default_recipients" "${SMTP_DEFAULT_RECIPIENTS}"
put_param "servicenow/enabled" "${SERVICENOW_ENABLED:-true}"
put_param "servicenow/instance_url" "${SERVICENOW_INSTANCE_URL}"
put_param "servicenow/username" "${SERVICENOW_USERNAME:-}"
put_param "servicenow/password" "${SERVICENOW_PASSWORD:-}"
put_param "servicenow/bearer_token" "${SERVICENOW_BEARER_TOKEN:-}"
put_param "servicenow/assignment_group" "${SERVICENOW_ASSIGNMENT_GROUP:-}"
put_param "servicenow/cmdb_ci" "${SERVICENOW_CMDB_CI:-}"
put_param "bedrock/model_id" "${BEDROCK_MODEL_ID}"
put_param "bedrock/max_tokens" "${BEDROCK_MAX_TOKENS:-2500}"
put_param "bedrock/temperature" "${BEDROCK_TEMPERATURE:-0.1}"
put_param "mcp/url" "http://127.0.0.1:8000/mcp"
put_param "allowed/account_ids" "${ALLOWED_ACCOUNT_IDS_JSON:-[]}"
put_param "allowed/regions" "${ALLOWED_REGIONS_JSON:-[\"us-gov-west-1\"]}"
put_param "allowed/alarm_name_patterns" "${ALLOWED_ALARM_NAME_PATTERNS_JSON:-[\"*\"]}"
echo "SecureString parameters written under ${PARAMETER_PREFIX}"
